# Generated by Django 2.2.10 on 2021-08-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anggota',
            new_name='Peserta',
        ),
    ]
