# Generated by Django 2.2.10 on 2021-08-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210806_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='alamat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
