# Generated by Django 2.2.10 on 2021-08-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210806_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='jurusan',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Jurusan'),
        ),
    ]
