# Generated by Django 2.2.10 on 2021-08-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210806_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKelamin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
    ]
