# Generated by Django 2.2.10 on 2021-08-06 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jeniskelamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='jenis_kelamin',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.JenisKelamin'),
        ),
    ]
