# Generated by Django 2.2.10 on 2021-08-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210807_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
