# Generated by Django 2.2.10 on 2021-08-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210807_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
